### ISSUE TITLE
Inquiry about `threads_api` abilities

### ISSUE THREAD

**Issue by Jexsie** [noahclark556/threads_api#4]
Hey @noahclark556, thanks for this great work. I would like to confirm something. Can this help me get access to threads videos once provide the video url? I know nothing about Python. Just confirming. Thanks

**Comment by noahclark556** [comment]
As of now, media access is not available. Although i do plan to add it in
the near future!

**Comment by Jexsie** [comment]
> As of now, media access is not available. Although i do plan to add it in the near future!


Roger. Thanks anyway. Is there anyway I can jump into now and help you with some tasks? Minor ones ofcourse

**Comment by noahclark556** [comment]
Absolutely, adjust as needed and send up a pull request. i’ll review and most likely merge it with main branch!

**Comment by noahclark556** [comment]
> > As of now, media access is not available. Although i do plan to add it in the near future!
> 
> Roger. Thanks anyway. Is there anyway I can jump into now and help you with some tasks? Minor ones ofcourse



> > As of now, media access is not available. Although i do plan to add it in the near future!
> 
> Roger. Thanks anyway. Is there anyway I can jump into now and help you with some tasks? Minor ones ofcourse

Absolutely, adjust as needed and send up a pull request. i’ll review and most likely merge it with main branch!
